/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2finalproject;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.InputMismatchException;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jon
 */
public class guiFinalProject extends javax.swing.JFrame {
    DefaultListModel model = new DefaultListModel();

    /**
     * Creates new form guiFinalProject
     */
    public guiFinalProject() {
        initComponents();
        lstLog.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMyName = new javax.swing.JLabel();
        lblGradeA = new javax.swing.JLabel();
        lblGradeB = new javax.swing.JLabel();
        lblGradeC = new javax.swing.JLabel();
        lblGradeD = new javax.swing.JLabel();
        lblGradeF = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblFinalPercent = new javax.swing.JLabel();
        lblPassThresh = new javax.swing.JLabel();
        lblLog = new javax.swing.JLabel();
        txtPassThresh = new javax.swing.JTextField();
        txtFName1 = new javax.swing.JTextField();
        txtFName2 = new javax.swing.JTextField();
        txtFName3 = new javax.swing.JTextField();
        txtFName4 = new javax.swing.JTextField();
        txtFName5 = new javax.swing.JTextField();
        txtLName1 = new javax.swing.JTextField();
        txtLName2 = new javax.swing.JTextField();
        txtLName3 = new javax.swing.JTextField();
        txtLName4 = new javax.swing.JTextField();
        txtLName5 = new javax.swing.JTextField();
        txtFinalPercent1 = new javax.swing.JTextField();
        txtFinalPercent2 = new javax.swing.JTextField();
        txtFinalPercent3 = new javax.swing.JTextField();
        txtFinalPercent4 = new javax.swing.JTextField();
        txtFinalPercent5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLog = new javax.swing.JList<>();
        btnSubmit1 = new javax.swing.JButton();
        btnSubmit2 = new javax.swing.JButton();
        btnSubmit3 = new javax.swing.JButton();
        btnSubmit4 = new javax.swing.JButton();
        btnSubmit5 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogSave = new javax.swing.JButton();
        btnLogLoad = new javax.swing.JButton();
        btnLogSummary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMyName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMyName.setText("JonBair Student Grade");

        lblGradeA.setText("A 90-100");

        lblGradeB.setText("B 80-89");

        lblGradeC.setText("C 70-79");

        lblGradeD.setText("D 60-69");

        lblGradeF.setText("F 59-");

        lblFName.setText("First Name");

        lblLName.setText("Last Name");

        lblFinalPercent.setText("Final Percentage");

        lblPassThresh.setText("Pass Threshold");

        lblLog.setText("Log");

        txtPassThresh.setText("60");
        txtPassThresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassThreshActionPerformed(evt);
            }
        });

        txtFName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFName2ActionPerformed(evt);
            }
        });

        txtLName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLName2ActionPerformed(evt);
            }
        });

        txtFinalPercent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalPercent1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstLog);

        btnSubmit1.setText("Submit");
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });

        btnSubmit2.setText("Submit");
        btnSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit2ActionPerformed(evt);
            }
        });

        btnSubmit3.setText("Submit");
        btnSubmit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit3ActionPerformed(evt);
            }
        });

        btnSubmit4.setText("Submit");
        btnSubmit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit4ActionPerformed(evt);
            }
        });

        btnSubmit5.setText("Submit");
        btnSubmit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit5ActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogSave.setText("Save");
        btnLogSave.setEnabled(false);
        btnLogSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogSaveActionPerformed(evt);
            }
        });

        btnLogLoad.setText("Load");
        btnLogLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogLoadActionPerformed(evt);
            }
        });

        btnLogSummary.setText("Summary");
        btnLogSummary.setEnabled(false);
        btnLogSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogSummaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMyName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFName)
                                .addGap(58, 58, 58)
                                .addComponent(lblLName)
                                .addGap(59, 59, 59)
                                .addComponent(lblFinalPercent))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFName1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLName1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFinalPercent1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFName5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLName5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFinalPercent5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFName2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLName2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFinalPercent2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFName3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLName3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFinalPercent3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFName4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLName4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFinalPercent4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(lblGradeA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGradeB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSubmit2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmit3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmit4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmit5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogSummary))
                    .addComponent(lblLog, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGradeC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGradeD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGradeF)
                        .addGap(25, 25, 25)
                        .addComponent(lblPassThresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassThresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMyName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGradeA)
                    .addComponent(lblGradeB)
                    .addComponent(lblGradeC)
                    .addComponent(lblGradeD)
                    .addComponent(lblGradeF)
                    .addComponent(lblPassThresh)
                    .addComponent(txtPassThresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName)
                    .addComponent(lblLName)
                    .addComponent(lblFinalPercent)
                    .addComponent(lblLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinalPercent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFinalPercent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSubmit2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSubmit3)
                                .addComponent(txtFinalPercent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinalPercent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinalPercent5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit5)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExit)
                        .addComponent(btnLogSave)
                        .addComponent(btnLogLoad)
                        .addComponent(btnLogSummary)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFName2ActionPerformed

    private void txtLName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLName2ActionPerformed

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
        try
        {
            String fn1 = txtFName1.getText();
            String ln1 = txtLName1.getText();
            String fp1 = txtFinalPercent1.getText();
            Double fpv1 = Double.valueOf(fp1);
            
            if(fn1.equals(""))
            {
                txtFName1.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(ln1.equals(""))
            {
                txtLName1.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(fpv1 >= 0 && fpv1 <= 100){}
            else
            {
                txtFinalPercent1.setText("");
                txtFinalPercent1.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: enter a valid number");
                return;
            }
                
            student student1 = new student(fpv1);
            student1.setFname(fn1);
            student1.setLname(ln1);
            student1.setGrade(fp1);
            
            String Fname = student1.getFname();
            String Lname = student1.getLname();
            String Percent = String.valueOf(student1.getPercentage());
            String Grade = student1.getGrade();
            
            model.addElement(Lname + ", " + Fname + " " + Percent + " - " + Grade);
            
            txtFName1.setEditable(false);
            txtFName1.setBackground(Color.gray);
            txtLName1.setEditable(false);
            txtLName1.setBackground(Color.gray);
            txtFinalPercent1.setEditable(false);
            txtFinalPercent1.setBackground(Color.gray);
            btnSubmit1.setEnabled(false);
        }
        catch(InputMismatchException a) {}
        catch(NumberFormatException n)
        {
            txtFinalPercent1.setText("");
            txtFinalPercent1.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Error: enter a valid number");
        }
        
        if(btnSubmit1.isEnabled() == false &&
           btnSubmit2.isEnabled() == false &&
           btnSubmit3.isEnabled() == false &&
           btnSubmit4.isEnabled() == false &&
           btnSubmit5.isEnabled() == false)
        {
            btnLogSave.setEnabled(true);
            btnLogLoad.setEnabled(false);
            btnLogSummary.setEnabled(true);
            txtPassThresh.setEditable(false);
            txtPassThresh.setBackground(Color.gray);
        }
    }//GEN-LAST:event_btnSubmit1ActionPerformed

    private void btnSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit2ActionPerformed
        try
        {
            String fn2 = txtFName2.getText();
            String ln2 = txtLName2.getText();
            String fp2 = txtFinalPercent2.getText();
            Double fpv2 = Double.valueOf(fp2);
            
            if(fn2.equals(""))
            {
                txtFName2.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(ln2.equals(""))
            {
                txtLName2.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(fpv2 >= 0 && fpv2 <= 100){}
            else
            {
                txtFinalPercent2.setText("");
                txtFinalPercent2.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: enter a valid number");
                return;
            }
            
            student student2 = new student(fpv2);
            student2.setFname(fn2);
            student2.setLname(ln2);
            student2.setGrade(fp2);
            
            String Fname = student2.getFname();
            String Lname = student2.getLname();
            String Percent = String.valueOf(student2.getPercentage());
            String Grade = student2.getGrade();
            
            model.addElement(Lname + ", " + Fname + " " + Percent + " - " + Grade);
            
            txtFName2.setEditable(false);
            txtFName2.setBackground(Color.gray);
            txtLName2.setEditable(false);
            txtLName2.setBackground(Color.gray);
            txtFinalPercent2.setEditable(false);
            txtFinalPercent2.setBackground(Color.gray);
            btnSubmit2.setEnabled(false);
        }
        catch(InputMismatchException a) {}
        catch(NumberFormatException n)
        {
            txtFinalPercent2.setText("");
            txtFinalPercent2.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Error: enter a valid number");
        }
        
        if(btnSubmit1.isEnabled() == false &&
           btnSubmit2.isEnabled() == false &&
           btnSubmit3.isEnabled() == false &&
           btnSubmit4.isEnabled() == false &&
           btnSubmit5.isEnabled() == false)
        {
            btnLogSave.setEnabled(true);
            btnLogLoad.setEnabled(false);
            btnLogSummary.setEnabled(true);
            txtPassThresh.setEditable(false);
            txtPassThresh.setBackground(Color.gray);
        }
    }//GEN-LAST:event_btnSubmit2ActionPerformed

    private void btnSubmit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit3ActionPerformed
        try
        {
            String fn3 = txtFName3.getText();
            String ln3 = txtLName3.getText();
            String fp3 = txtFinalPercent3.getText();
            Double fpv3 = Double.valueOf(fp3);
            
            if(fn3.equals(""))
            {
                txtFName3.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(ln3.equals(""))
            {
                txtLName3.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(fpv3 >= 0 && fpv3 <= 100){}
            else
            {
                txtFinalPercent3.setText("");
                txtFinalPercent3.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: enter a valid number");
                return;
            }
            
            student student3 = new student(fpv3);
            student3.setFname(fn3);
            student3.setLname(ln3);
            student3.setGrade(fp3);
            
            String Fname = student3.getFname();
            String Lname = student3.getLname();
            String Percent = String.valueOf(student3.getPercentage());
            String Grade = student3.getGrade();
            
            model.addElement(Lname + ", " + Fname + " " + Percent + " - " + Grade);
            
            txtFName3.setEditable(false);
            txtFName3.setBackground(Color.gray);
            txtLName3.setEditable(false);
            txtLName3.setBackground(Color.gray);
            txtFinalPercent3.setEditable(false);
            txtFinalPercent3.setBackground(Color.gray);
            btnSubmit3.setEnabled(false);
        }
        catch(InputMismatchException a) {}
        catch(NumberFormatException n)
        {
            txtFinalPercent3.setText("");
            txtFinalPercent3.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Error: enter a valid number");
        }
        
        if(btnSubmit1.isEnabled() == false &&
           btnSubmit2.isEnabled() == false &&
           btnSubmit3.isEnabled() == false &&
           btnSubmit4.isEnabled() == false &&
           btnSubmit5.isEnabled() == false)
        {
            btnLogSave.setEnabled(true);
            btnLogLoad.setEnabled(false);
            btnLogSummary.setEnabled(true);
            txtPassThresh.setEditable(false);
            txtPassThresh.setBackground(Color.gray);
        }
    }//GEN-LAST:event_btnSubmit3ActionPerformed

    private void btnSubmit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit4ActionPerformed
        try
        {
            String fn4 = txtFName4.getText();
            String ln4 = txtLName4.getText();
            String fp4 = txtFinalPercent4.getText();
            Double fpv4 = Double.valueOf(fp4);
            
            if(fn4.equals(""))
            {
                txtFName4.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(ln4.equals(""))
            {
                txtLName4.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(fpv4 >= 0 && fpv4 <= 100){}
            else
            {
                txtFinalPercent4.setText("");
                txtFinalPercent4.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: enter a valid number");
                return;
            }
            
            student student4 = new student(fpv4);
            student4.setFname(fn4);
            student4.setLname(ln4);
            student4.setGrade(fp4);
            
            String Fname = student4.getFname();
            String Lname = student4.getLname();
            String Percent = String.valueOf(student4.getPercentage());
            String Grade = student4.getGrade();
            
            model.addElement(Lname + ", " + Fname + " " + Percent + " - " + Grade);
            
            txtFName4.setEditable(false);
            txtFName4.setBackground(Color.gray);
            txtLName4.setEditable(false);
            txtLName4.setBackground(Color.gray);
            txtFinalPercent4.setEditable(false);
            txtFinalPercent4.setBackground(Color.gray);
            btnSubmit4.setEnabled(false);
        }
        catch(InputMismatchException a) {}
        catch(NumberFormatException n)
        {
            txtFinalPercent4.setText("");
            txtFinalPercent4.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Error: enter a valid number");
        }
        
        if(btnSubmit1.isEnabled() == false &&
           btnSubmit2.isEnabled() == false &&
           btnSubmit3.isEnabled() == false &&
           btnSubmit4.isEnabled() == false &&
           btnSubmit5.isEnabled() == false)
        {
            btnLogSave.setEnabled(true);
            btnLogLoad.setEnabled(false);
            btnLogSummary.setEnabled(true);
            txtPassThresh.setEditable(false);
            txtPassThresh.setBackground(Color.gray);
        }
    }//GEN-LAST:event_btnSubmit4ActionPerformed

    private void btnSubmit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit5ActionPerformed
        try
        {
            String fn5 = txtFName5.getText();
            String ln5 = txtLName5.getText();
            String fp5 = txtFinalPercent5.getText();
            Double fpv5 = Double.valueOf(fp5);
            
            if(fn5.equals(""))
            {
                txtFName5.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(ln5.equals(""))
            {
                txtLName5.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: box is empty");
                return;
            }
            
            if(fpv5 >= 0 && fpv5 <= 100){}
            else
            {
                txtFinalPercent5.setText("");
                txtFinalPercent5.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: enter a valid number");
                return;
            }
            
            student student5 = new student(fpv5);
            student5.setFname(fn5);
            student5.setLname(ln5);
            student5.setGrade(fp5);
            
            String Fname = student5.getFname();
            String Lname = student5.getLname();
            String Percent = String.valueOf(student5.getPercentage());
            String Grade = student5.getGrade();
            
            model.addElement(Lname + ", " + Fname + " " + Percent + " - " + Grade);
            
            txtFName5.setEditable(false);
            txtFName5.setBackground(Color.gray);
            txtLName5.setEditable(false);
            txtLName5.setBackground(Color.gray);
            txtFinalPercent5.setEditable(false);
            txtFinalPercent5.setBackground(Color.gray);
            btnSubmit5.setEnabled(false);
        }
        catch(InputMismatchException a) {}
        catch(NumberFormatException n)
        {
            txtFinalPercent5.setText("");
            txtFinalPercent5.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Error: enter a valid number");
        }
        
        if(btnSubmit1.isEnabled() == false &&
           btnSubmit2.isEnabled() == false &&
           btnSubmit3.isEnabled() == false &&
           btnSubmit4.isEnabled() == false &&
           btnSubmit5.isEnabled() == false)
        {
            btnLogSave.setEnabled(true);
            btnLogLoad.setEnabled(false);
            btnLogSummary.setEnabled(true);
            txtPassThresh.setEditable(false);
            txtPassThresh.setBackground(Color.gray);
        }
        
    }//GEN-LAST:event_btnSubmit5ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtFName1.setText("");
        txtFName1.setEditable(true);
        txtFName1.setBackground(Color.white);
        txtLName1.setText("");
        txtLName1.setEditable(true);
        txtLName1.setBackground(Color.white);
        txtFinalPercent1.setText("");
        txtFinalPercent1.setEditable(true);
        txtFinalPercent1.setBackground(Color.white);
        btnSubmit1.setEnabled(true);
        
        txtFName2.setText("");
        txtFName2.setEditable(true);
        txtFName2.setBackground(Color.white);
        txtLName2.setText("");
        txtLName2.setEditable(true);
        txtLName2.setBackground(Color.white);
        txtFinalPercent2.setText("");
        txtFinalPercent2.setEditable(true);
        txtFinalPercent2.setBackground(Color.white);
        btnSubmit2.setEnabled(true);
        
        txtFName3.setText("");
        txtFName3.setEditable(true);
        txtFName3.setBackground(Color.white);
        txtLName3.setText("");
        txtLName3.setEditable(true);
        txtLName3.setBackground(Color.white);
        txtFinalPercent3.setText("");
        txtFinalPercent3.setEditable(true);
        txtFinalPercent3.setBackground(Color.white);
        btnSubmit3.setEnabled(true);
        
        txtFName4.setText("");
        txtFName4.setEditable(true);
        txtFName4.setBackground(Color.white);
        txtLName4.setText("");
        txtLName4.setEditable(true);
        txtLName4.setBackground(Color.white);
        txtFinalPercent4.setText("");
        txtFinalPercent4.setEditable(true);
        txtFinalPercent4.setBackground(Color.white);
        btnSubmit4.setEnabled(true);
        
        txtFName5.setText("");
        txtFName5.setEditable(true);
        txtFName5.setBackground(Color.white);
        txtLName5.setText("");
        txtLName5.setEditable(true);
        txtLName5.setBackground(Color.white);
        txtFinalPercent5.setText("");
        txtFinalPercent5.setEditable(true);
        txtFinalPercent5.setBackground(Color.white);
        btnSubmit5.setEnabled(true);
        
        btnLogSave.setEnabled(false);
        btnLogSummary.setEnabled(false);
        btnLogLoad.setEnabled(true);
        txtPassThresh.setEditable(true);
        txtPassThresh.setBackground(Color.white);
        model.clear();
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtFinalPercent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalPercent1ActionPerformed
        
    }//GEN-LAST:event_txtFinalPercent1ActionPerformed

    private void btnLogSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogSaveActionPerformed
        File f = new File("Students.txt");
        
        try
        {
            PrintWriter out = new PrintWriter(f);
            out.println(txtLName1.getText());
            out.println(txtFName1.getText());
            out.println(txtFinalPercent1.getText());
            
            out.println(txtLName2.getText());
            out.println(txtFName2.getText());
            out.println(txtFinalPercent2.getText());
            
            out.println(txtLName3.getText());
            out.println(txtFName3.getText());
            out.println(txtFinalPercent3.getText());
            
            out.println(txtLName4.getText());
            out.println(txtFName4.getText());
            out.println(txtFinalPercent4.getText());
            
            out.println(txtLName5.getText());
            out.println(txtFName5.getText());
            out.println(txtFinalPercent5.getText());
            out.close();
        }
        catch(IOException ex)
        {
            System.out.println("File not found");
        }
    }//GEN-LAST:event_btnLogSaveActionPerformed

    private void btnLogSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogSummaryActionPerformed
        try
        {
        model.addElement("");
        
        String pt = txtPassThresh.getText();
        String fp1 = txtFinalPercent1.getText();
        String fp2 = txtFinalPercent2.getText();
        String fp3 = txtFinalPercent3.getText();
        String fp4 = txtFinalPercent4.getText();
        String fp5 = txtFinalPercent5.getText();
        
        if(pt.equals(""))
        {
            txtPassThresh.setEditable(true);
            txtPassThresh.setBackground(Color.white);
            txtPassThresh.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Error: box is empty");
            return;
        }
        
        Double ptv = Double.valueOf(pt);
        Double fpv1 = Double.valueOf(fp1);
        Double fpv2 = Double.valueOf(fp2);
        Double fpv3 = Double.valueOf(fp3);
        Double fpv4 = Double.valueOf(fp4);
        Double fpv5 = Double.valueOf(fp5);
        
        if(ptv >= 0 && ptv <= 100){}
            else
            {
                txtPassThresh.setText("");
                txtPassThresh.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Error: enter a valid number for pass threshold");
                return;
            }
        
        int pass = 0, fail = 0;
        
        if(fpv1 >= ptv)
            pass++;
        else
            fail++;
        
        if(fpv2 >= ptv)
            pass++;
        else
            fail++;
        
        if(fpv3 >= ptv)
            pass++;
        else
            fail++;
        
        if(fpv4 >= ptv)
            pass++;
        else
            fail++;
        
        if(fpv5 >= ptv)
            pass++;
        else
            fail++;
        
        model.addElement("PASS: " + pass + "     " + "FAIL: " + fail);
        }
        catch(NumberFormatException n)
        {
            txtPassThresh.setText("");
            txtPassThresh.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Error: enter a valid number for pass threshold");
        }
    }//GEN-LAST:event_btnLogSummaryActionPerformed

    private void txtPassThreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassThreshActionPerformed
        
    }//GEN-LAST:event_txtPassThreshActionPerformed

    private void btnLogLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogLoadActionPerformed
        try(FileReader fr = new FileReader("Students.txt"))
        {
            // This was most certainly not the most efficient way, but I was
            // struggling to figure this part out another way, I would of course
            // like to know how best to do this part
            Scanner scan = new Scanner(fr);
            String ln1 = scan.next();
            String fn1 = scan.next();
            String fp1 = scan.next();
            String ln2 = scan.next();
            String fn2 = scan.next();
            String fp2 = scan.next();
            String ln3 = scan.next();
            String fn3 = scan.next();
            String fp3 = scan.next();
            String ln4 = scan.next();
            String fn4 = scan.next();
            String fp4 = scan.next();
            String ln5 = scan.next();
            String fn5 = scan.next();
            String fp5 = scan.next();
            
            txtLName1.setText(ln1);
            txtFName1.setText(fn1);
            txtFinalPercent1.setText(fp1);
            txtLName2.setText(ln2);
            txtFName2.setText(fn2);
            txtFinalPercent2.setText(fp2);
            txtLName3.setText(ln3);
            txtFName3.setText(fn3);
            txtFinalPercent3.setText(fp3);
            txtLName4.setText(ln4);
            txtFName4.setText(fn4);
            txtFinalPercent4.setText(fp4);
            txtLName5.setText(ln5);
            txtFName5.setText(fn5);
            txtFinalPercent5.setText(fp5);
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(null, "Error: file not found to load from");
        }
    }//GEN-LAST:event_btnLogLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiFinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiFinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiFinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiFinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiFinalProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogLoad;
    private javax.swing.JButton btnLogSave;
    private javax.swing.JButton btnLogSummary;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JButton btnSubmit2;
    private javax.swing.JButton btnSubmit3;
    private javax.swing.JButton btnSubmit4;
    private javax.swing.JButton btnSubmit5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFinalPercent;
    private javax.swing.JLabel lblGradeA;
    private javax.swing.JLabel lblGradeB;
    private javax.swing.JLabel lblGradeC;
    private javax.swing.JLabel lblGradeD;
    private javax.swing.JLabel lblGradeF;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblMyName;
    private javax.swing.JLabel lblPassThresh;
    private javax.swing.JList<String> lstLog;
    private javax.swing.JTextField txtFName1;
    private javax.swing.JTextField txtFName2;
    private javax.swing.JTextField txtFName3;
    private javax.swing.JTextField txtFName4;
    private javax.swing.JTextField txtFName5;
    private javax.swing.JTextField txtFinalPercent1;
    private javax.swing.JTextField txtFinalPercent2;
    private javax.swing.JTextField txtFinalPercent3;
    private javax.swing.JTextField txtFinalPercent4;
    private javax.swing.JTextField txtFinalPercent5;
    private javax.swing.JTextField txtLName1;
    private javax.swing.JTextField txtLName2;
    private javax.swing.JTextField txtLName3;
    private javax.swing.JTextField txtLName4;
    private javax.swing.JTextField txtLName5;
    private javax.swing.JTextField txtPassThresh;
    // End of variables declaration//GEN-END:variables
}
